import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'About',
  description: 'Learn about AI Line Detector, a free tool to spot AI-written text line by line.',
};

export default function AboutPage() {
  return (
    <main className="max-w-2xl mx-auto px-6 py-16 prose prose-neutral">
      <h1 className="font-serif">About</h1>
      <p>
        AI Line Detector is a free tool that helps you spot which lines in a
        passage read as AI-written versus human-written. Paste any text and
        get an instant, line-by-line breakdown.
      </p>
      <p>
        Built for writers, editors, teachers, and anyone who wants a quick
        sanity check on whether text was likely generated by tools like
        ChatGPT, Gemini, or Claude.
      </p>
      {/* Replace with your real story/bio */}
      <p>
        This project was built by Praful Tiwari, focused on making AI
        detection transparent and easy to use.
      </p>
    </main>
  );
}
